# Change these first
owner: Official-Hawks # Your GitHub organization or username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Hawkscord - Site
    url: https://hawkscord.dev
  - name: Hawkscord - CDN
    url: https://i-work-for.hawkscord.dev
  - name: Discord - Site
    url: https://discord.com
  - name: Discord - CDN
    url: https://cdn.discordapp.com

status-website:
themeUrl: https://uptime.hawkscord.dev/assets/css.css
#  cname: uptime.hawkscord.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
#  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
